name: dona_lordes
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1  # Adicione uma versão (obrigatório para publicação)

environment:
  sdk: ">=3.7.2 <4.0.0"  # Melhor forma de definir a restrição

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  url_launcher: ^6.1.11
  font_awesome_flutter: ^10.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  fonts:
    - family: DancingScript
      fonts:
        - asset: assets/fonts/DancingScript-Regular.ttf

  assets:
    - assets/images/background.jpg